package sockopt

// #include <srt/srt.h>
import "C"

type Sockopt C.SRT_SOCKOPT

const (
	MSS                 = Sockopt(C.SRTO_MSS)
	SNDSYN              = Sockopt(C.SRTO_SNDSYN)
	RCVSYN              = Sockopt(C.SRTO_RCVSYN)
	ISN                 = Sockopt(C.SRTO_ISN)
	FC                  = Sockopt(C.SRTO_FC)
	SNDBUF              = Sockopt(C.SRTO_SNDBUF)
	RCVBUF              = Sockopt(C.SRTO_RCVBUF)
	LINGER              = Sockopt(C.SRTO_LINGER)
	UDP_SNDBUF          = Sockopt(C.SRTO_UDP_SNDBUF)
	UDP_RCVBUF          = Sockopt(C.SRTO_UDP_RCVBUF)
	RENDEZVOUS          = Sockopt(C.SRTO_RENDEZVOUS)
	SNDTIMEO            = Sockopt(C.SRTO_SNDTIMEO)
	RCVTIMEO            = Sockopt(C.SRTO_RCVTIMEO)
	REUSEADDR           = Sockopt(C.SRTO_REUSEADDR)
	MAXBW               = Sockopt(C.SRTO_MAXBW)
	STATE               = Sockopt(C.SRTO_STATE)
	EVENT               = Sockopt(C.SRTO_EVENT)
	SNDDATA             = Sockopt(C.SRTO_SNDDATA)
	RCVDATA             = Sockopt(C.SRTO_RCVDATA)
	SENDER              = Sockopt(C.SRTO_SENDER)
	TSBPDMODE           = Sockopt(C.SRTO_TSBPDMODE)
	LATENCY             = Sockopt(C.SRTO_LATENCY)
	INPUTBW             = Sockopt(C.SRTO_INPUTBW)
	OHEADBW             = Sockopt(C.SRTO_OHEADBW)
	PASSPHRASE          = Sockopt(C.SRTO_PASSPHRASE)
	PBKEYLEN            = Sockopt(C.SRTO_PBKEYLEN)
	KMSTATE             = Sockopt(C.SRTO_KMSTATE)
	IPTTL               = Sockopt(C.SRTO_IPTTL)
	IPTOS               = Sockopt(C.SRTO_IPTOS)
	TLPKTDROP           = Sockopt(C.SRTO_TLPKTDROP)
	SNDDROPDELAY        = Sockopt(C.SRTO_SNDDROPDELAY)
	NAKREPORT           = Sockopt(C.SRTO_NAKREPORT)
	VERSION             = Sockopt(C.SRTO_VERSION)
	PEERVERSION         = Sockopt(C.SRTO_PEERVERSION)
	CONNTIMEO           = Sockopt(C.SRTO_CONNTIMEO)
	DRIFTTRACER         = Sockopt(C.SRTO_DRIFTTRACER)
	MININPUTBW          = Sockopt(C.SRTO_MININPUTBW)
	SNDKMSTATE          = Sockopt(C.SRTO_SNDKMSTATE)
	RCVKMSTATE          = Sockopt(C.SRTO_RCVKMSTATE)
	LOSSMAXTTL          = Sockopt(C.SRTO_LOSSMAXTTL)
	RCVLATENCY          = Sockopt(C.SRTO_RCVLATENCY)
	PEERLATENCY         = Sockopt(C.SRTO_PEERLATENCY)
	MINVERSION          = Sockopt(C.SRTO_MINVERSION)
	STREAMID            = Sockopt(C.SRTO_STREAMID)
	CONGESTION          = Sockopt(C.SRTO_CONGESTION)
	MESSAGEAPI          = Sockopt(C.SRTO_MESSAGEAPI)
	PAYLOADSIZE         = Sockopt(C.SRTO_PAYLOADSIZE)
	TRANSTYPE           = Sockopt(C.SRTO_TRANSTYPE)
	KMREFRESHRATE       = Sockopt(C.SRTO_KMREFRESHRATE)
	KMPREANNOUNCE       = Sockopt(C.SRTO_KMPREANNOUNCE)
	ENFORCEDENCRYPTION  = Sockopt(C.SRTO_ENFORCEDENCRYPTION)
	IPV6ONLY            = Sockopt(C.SRTO_IPV6ONLY)
	PEERIDLETIMEO       = Sockopt(C.SRTO_PEERIDLETIMEO)
	BINDTODEVICE        = Sockopt(C.SRTO_BINDTODEVICE)
	GROUPCONNECT        = Sockopt(C.SRTO_GROUPCONNECT)
	GROUPMINSTABLETIMEO = Sockopt(C.SRTO_GROUPMINSTABLETIMEO)
	GROUPTYPE           = Sockopt(C.SRTO_GROUPTYPE)
	PACKETFILTER        = Sockopt(C.SRTO_PACKETFILTER)
	RETRANSMITALGO      = Sockopt(C.SRTO_RETRANSMITALGO)
	E_SIZE              = Sockopt(C.SRTO_E_SIZE)
)
